/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryShilohranch.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLQueryShilohranch (10 custom class methods, 6 custom properties)

#import "GTLQueryShilohranch.h"

#import "GTLShilohranchCategoryCollection.h"
#import "GTLShilohranchDeletionCollection.h"
#import "GTLShilohranchEventCollection.h"
#import "GTLShilohranchPostCollection.h"
#import "GTLShilohranchSermonCollection.h"
#import "GTLShilohranchUpdate.h"

@implementation GTLQueryShilohranch

@dynamic fields, lastSync, limit, milliseconds, pageToken, timeZoneOffset;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map = @{
    @"timeZoneOffset" : @"time_zone_offset"
  };
  return map;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryShilohranch object.

+ (instancetype)queryForCategories {
  NSString *methodName = @"shilohranch.categories";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShilohranchCategoryCollection class];
  return query;
}

+ (instancetype)queryForDeletions {
  NSString *methodName = @"shilohranch.deletions";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShilohranchDeletionCollection class];
  return query;
}

+ (instancetype)queryForEvents {
  NSString *methodName = @"shilohranch.events";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShilohranchEventCollection class];
  return query;
}

+ (instancetype)queryForPosts {
  NSString *methodName = @"shilohranch.posts";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShilohranchPostCollection class];
  return query;
}

+ (instancetype)queryForSermons {
  NSString *methodName = @"shilohranch.sermons";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShilohranchSermonCollection class];
  return query;
}

#pragma mark -
#pragma mark "update" methods
// These create a GTLQueryShilohranch object.

+ (instancetype)queryForUpdateCategoriesWithMilliseconds:(long long)milliseconds {
  NSString *methodName = @"shilohranch.update.categories";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.milliseconds = milliseconds;
  query.expectedObjectClass = [GTLShilohranchUpdate class];
  return query;
}

+ (instancetype)queryForUpdateDeletionsWithMilliseconds:(long long)milliseconds {
  NSString *methodName = @"shilohranch.update.deletions";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.milliseconds = milliseconds;
  query.expectedObjectClass = [GTLShilohranchUpdate class];
  return query;
}

+ (instancetype)queryForUpdateEventsWithMilliseconds:(long long)milliseconds {
  NSString *methodName = @"shilohranch.update.events";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.milliseconds = milliseconds;
  query.expectedObjectClass = [GTLShilohranchUpdate class];
  return query;
}

+ (instancetype)queryForUpdatePostsWithMilliseconds:(long long)milliseconds {
  NSString *methodName = @"shilohranch.update.posts";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.milliseconds = milliseconds;
  query.expectedObjectClass = [GTLShilohranchUpdate class];
  return query;
}

+ (instancetype)queryForUpdateSermonsWithMilliseconds:(long long)milliseconds {
  NSString *methodName = @"shilohranch.update.sermons";
  GTLQueryShilohranch *query = [self queryWithMethodName:methodName];
  query.milliseconds = milliseconds;
  query.expectedObjectClass = [GTLShilohranchUpdate class];
  return query;
}

@end
