/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchPost.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchPost (0 custom class methods, 6 custom properties)

#import "GTLShilohranchPost.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchPost
//

@implementation GTLShilohranchPost
@dynamic category, content, date, entityKey, timeAdded, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"timeAdded" : @"time_added"
  };
  return map;
}

@end
