/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchEvent.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchEvent (0 custom class methods, 8 custom properties)

#import "GTLShilohranchEvent.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchEvent
//

@implementation GTLShilohranchEvent
@dynamic content, endTime, entityKey, location, repeat, startTime, timeAdded,
         title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"endTime" : @"end_time",
    @"startTime" : @"start_time",
    @"timeAdded" : @"time_added"
  };
  return map;
}

@end
