/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API

#import "GTLShilohranchConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeShilohranchUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
