/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchDeletion.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchDeletion (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLShilohranchDeletion
//

@interface GTLShilohranchDeletion : GTLObject
@property (nonatomic, copy) NSString *deletionKey;
@property (nonatomic, copy) NSString *entityKey;
@property (nonatomic, copy) NSString *kind;
@property (nonatomic, copy) NSString *timeAdded;
@end
