/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchEvent.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchEvent (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLShilohranchEvent
//

@interface GTLShilohranchEvent : GTLObject
@property (nonatomic, copy) NSString *content;
@property (nonatomic, copy) NSString *endTime;
@property (nonatomic, copy) NSString *entityKey;
@property (nonatomic, copy) NSString *location;
@property (nonatomic, copy) NSString *repeat;
@property (nonatomic, copy) NSString *startTime;
@property (nonatomic, copy) NSString *timeAdded;
@property (nonatomic, copy) NSString *title;
@end
