/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchDeletionCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchDeletionCollection (0 custom class methods, 2 custom properties)

#import "GTLShilohranchDeletionCollection.h"

#import "GTLShilohranchDeletion.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchDeletionCollection
//

@implementation GTLShilohranchDeletionCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLShilohranchDeletion class]
  };
  return map;
}

@end
