/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchDeletion.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchDeletion (0 custom class methods, 4 custom properties)

#import "GTLShilohranchDeletion.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchDeletion
//

@implementation GTLShilohranchDeletion
@dynamic deletionKey, entityKey, kind, timeAdded;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"deletionKey" : @"deletion_key",
    @"timeAdded" : @"time_added"
  };
  return map;
}

@end
