/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranch.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API

#import "GTLShilohranchConstants.h"

#import "GTLShilohranchCategory.h"
#import "GTLShilohranchCategoryCollection.h"
#import "GTLShilohranchDeletion.h"
#import "GTLShilohranchDeletionCollection.h"
#import "GTLShilohranchEvent.h"
#import "GTLShilohranchEventCollection.h"
#import "GTLShilohranchPost.h"
#import "GTLShilohranchPostCollection.h"
#import "GTLShilohranchSermon.h"
#import "GTLShilohranchSermonCollection.h"
#import "GTLShilohranchUpdate.h"

#import "GTLQueryShilohranch.h"
#import "GTLServiceShilohranch.h"
