/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchCategoryCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchCategoryCollection (0 custom class methods, 2 custom properties)

#import "GTLShilohranchCategoryCollection.h"

#import "GTLShilohranchCategory.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchCategoryCollection
//

@implementation GTLShilohranchCategoryCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLShilohranchCategory class]
  };
  return map;
}

@end
