/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchSermon.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchSermon (0 custom class methods, 5 custom properties)

#import "GTLShilohranchSermon.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchSermon
//

@implementation GTLShilohranchSermon
@dynamic audioLink, date, entityKey, timeAdded, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"audioLink" : @"audio_link",
    @"timeAdded" : @"time_added"
  };
  return map;
}

@end
