/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchUpdate.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchUpdate (0 custom class methods, 1 custom properties)

#import "GTLShilohranchUpdate.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchUpdate
//

@implementation GTLShilohranchUpdate
@dynamic needsUpdate;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"needsUpdate" : @"needs_update"
  };
  return map;
}

@end
