/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLShilohranchEventCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shilohranch/v1
// Description:
//   Shiloh Ranch Mobile App API
// Classes:
//   GTLShilohranchEventCollection (0 custom class methods, 2 custom properties)

#import "GTLShilohranchEventCollection.h"

#import "GTLShilohranchEvent.h"

// ----------------------------------------------------------------------------
//
//   GTLShilohranchEventCollection
//

@implementation GTLShilohranchEventCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLShilohranchEvent class]
  };
  return map;
}

@end
